### ISSUE TITLE
rlang::last_error() 

### ISSUE THREAD

**Issue by jiangweixia** [JH-Zhou/HandyCNV#11]
I'm sorry to bother you, when I used the cnv_clean() function, my input CNV data was calculated by the PennCNV software. 

while I have a bug,  the bug  was 

ERROR: can't find "V8", Run `rlang::last_error()` to see where the error occurred.
In addition: 
Warning message: Expected 2 pieces. Missing pieces filled with `NA` in 33766 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 , 12, 13, 14, 15, 16, 17, 18, 19, 20, ...].

**Comment by JH-Zhou** [comment]
Hi, thank you for your question. Is your last column is 'endsnp= someSNPname' in PennCNV results? I suppose you didn't use '-confidence' flag while running 'detect.pl' of PennCNV, you may have 7 columns in CNV result instead of 8. I have updated the cnv_clean() function, it now should working on the list with 7 columns. Please update the package and try it again, if it still can not work please feel free to contact me.

**Comment by jiangweixia** [comment]
Yes, you are right. 
Thank you very much.
